### ISSUE TITLE
Few small todo's

### ISSUE THREAD

**Issue by MatthiasvdBelt** [MatthiasvdBelt/CAGECAT#46]
- [x] Tool explanation: titles are not equal in size
- [ ] Shorten title for clinker at explanation page
- [x] Remove accordeons
- [x] Create index at tool explanation page
- [x] Remove renderHelpTexts function in macros
